defaults: &defaults
  working_directory: ~/src
  docker:
    - image: circleci/node:8.4

version: 2
jobs:
  check-publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: check-publish
          command: ./check-publish-version

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: publish
          command: npm publish

workflows:
  version: 2

  check-publish:
    jobs:
      - check-publish:
          filters:
            branches:
              ignore:
                - master
      - publish:
          requires: 
            - check-publish
          filters:
            branches:
              only:
                - master
        